# =========================================================
# ANIMATIONS
# =========================================================

animations {
    enabled = true

    bezier = snap,      0.05, 0.9,  0.1,  1.05
    bezier = smooth,    0.4,  0.0,  0.2,  1.0
    bezier = bounce,    0.2,  1.6,  0.4,  1.0
    bezier = linear,    0.0,  0.0,  1.0,  1.0
    bezier = popIn,     0.1,  1.2,  0.3,  1.0
    bezier = slideOut,  0.4,  0.0,  1.0,  1.0

    animation = windowsIn,        1, 4, popIn,    popin 70%
    animation = windowsOut,       1, 3, slideOut, popin 80%
    animation = windowsMove,      1, 4, smooth
    animation = border,           1, 6, linear
    animation = borderangle,      1, 60, linear,  loop
    animation = fadeIn,           1, 4, smooth
    animation = fadeOut,          1, 3, smooth
    animation = fadeLayers,       1, 3, smooth
    animation = fadeSwitch,       1, 4, smooth
    animation = workspaces,       1, 4, bounce,   slide
    animation = specialWorkspace, 1, 4, smooth,   slidevert
}
