color0 #101414
color1 #ffb4ab
color2 #4dd9e5
color3 #b1cbce
color4 #b7c7ea
color5 #4dd9e5
color6 #b1cbce
color7 #e0e3e3
color8 #899393
color9 #ffb4ab
color10 #4dd9e5
color11 #b1cbce
color12 #b7c7ea
color13 #4dd9e5
color14 #b1cbce
color15 #e0e3e3

cursor                #e0e3e3
cursor_text_color     #101414
background            #101414
foreground            #e0e3e3
selection_foreground  #bec8c9
selection_background  #3f4849
active_border_color   #4dd9e5
inactive_border_color #3f4849
url_color             #4dd9e5

active_tab_foreground   #00363b
active_tab_background   #4dd9e5
inactive_tab_foreground #bec8c9
inactive_tab_background #3f4849
cursor_trail_color      #bec8c9
